name: Build SunamoStringGetString

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringGetString
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringGetString/SunamoStringGetString.csproj

    - name: Build
      run: dotnet build SunamoStringGetString/SunamoStringGetString.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringGetString.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringGetString.Tests/SunamoStringGetString.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringGetString.Tests/SunamoStringGetString.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringGetString.Tests/SunamoStringGetString.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
